baseURL = 'https://www.mulletranch.org'
title = 'Mullét Ranch'
theme = 'ananke'
languageCode = "en-us"
resourceDir = "../resources"

[params]
    background_color_class = "bg-black"
    body_classes = "bg-black"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"